version: "2"
services:
    cassandra:
      image: cassandra:3
      ports:
        - "7199:7199" # JMX
        - "7000:7000" # Internode
        - "7001:7001" # Internode (TLS)
        - "9160:9160" # Thrift client API
        - "9042:9042" # CQL Native transport
      volumes:
        - dbauth-data:/dataauth
    rabbit:
      image: rabbitmq:3.6-management
      ports:
        - "5672:5672"
        - "15672:15672"
    venus:
      build: ./docker
      image: karoku-docker-public.bintray.io/venus
      links:
        - cassandra:cassandra
        - rabbit:rabbit
      entrypoint:
        - /home/user/dev-entrypoint.sh
      volumes:
        - $PWD:/home/user/ws
        - $HOME/.m2:/home/user/.m2
        - $HOME/.gradle:/home/user/.gradle
        - $HOME/.groovy:/home/user/.groovy
        - $HOME/.sdkman/archives:/home/user/.sdkman/archives
        - $HOME/.sdkman/candidates:/home/user/.sdkman/candidates

volumes:
  dbauth-data:
